class AppConstants {
  static const String stringPlaceHolder = "-",
      localeAr = "ar",
      localeEn = "en",
      userId = "userId",
      partnerId = "partnerId",
      name = "name",
      emailId = "emailId",
      password = "password",
      role = "role",
      accessToken = 'access_token',
      selectedLanguage = 'selected_language',
      sessionId = 'session_id',
      languageCode = "language_code",
      biometricEnable = "biometric_enable",
      pinEnable = "pin_enable",
      countryCode = "country_code",
      isRememberMe = "isRememberMe",
      errorMsg = "Something went wrong.",
      companyId = 'companyId',
      isAppLaunchedFirstTime = 'isAppLaunchedFirstTime',
      maxWrittenConsultationResponseHours =
          "maxWrittenConsultationResponseHours",
      dateFormat = "yyyy-MM-dd";
}
